CREATE DATABASE DIO_SERIES;

USE DIO_SERIES;

CREATE TABLE SERIES(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    GENERO INT NOT NULL,
    TITULO TEXT(50) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    ANO INT UNSIGNED NOT NULL,
    DELETEDAT DATETIME 
);